Service class for the remaining 5 tables
ep-accelerators/learning pull request #18
Opened 2020-10-12 17:26 UTC by Midhun-h4r

#6 
Service class for the tables:
1.PickList
2.Login
3.Exam Answers
4.Exam Registration
5.Exam Schedule

2020-10-12 17:30 UTC, rahulreghunath requested changes
Change all variable name to camel case (eg $examSchedule)

2020-10-12 17:48 UTC, rahulreghunath requested changes

2020-10-12 17:48 UTC, rahulreghunath commented on app/Service/ExamAnswersService.php
> +        $examAnswers = ExamAnswers::findOrFail($id);
if the data in the variable is single just use singular variable names as a good practice. Here change $examAnswers to $examAnswer

2020-10-12 17:48 UTC, rahulreghunath commented on app/Service/ExamRegistrationService.php
> +        $ExamRegistration = new ExamRegistration();
Naming changes again :sweat_smile:

2020-10-12 17:50 UTC, Midhun-h4r reviewed
variable name corrected.

2020-10-12 18:02 UTC, rahulreghunath reviewed
Some more small changes

2020-10-13 15:09 UTC, rahulreghunath commented on app/Service/LoginService.php
> +        $Login = $this->find($id);
:smile:

2020-10-13 15:10 UTC, rahulreghunath approved these changes

2020-10-13 15:10 UTC, merged