Questionsetitem form created
ep-accelerators/learning pull request #37
Opened 2020-10-17 17:13 UTC by Midhun-h4r

#30 
Question Set item form created.

2020-10-17 18:41 UTC, rahulreghunath requested changes
Edit function is not in the issue but partially done, good. Some small changes need to be done, otherwise, look fine.

2020-10-17 18:41 UTC, rahulreghunath commented on resources/views/wisehabit/question_set_item.blade.php
> +                <option disabled @if(empty(old('question_set_id' ))) selected @endif>Choose Question Set Id</option>
Choose Question Set Id to Choose Question Set

2020-10-17 18:41 UTC, rahulreghunath commented on resources/views/wisehabit/question_set_item.blade.php
> +                <option disabled @if(empty(old('question_id' ))) selected @endif>Choose Question Id</option>
Choose Question Id to Choose Question

2020-10-17 18:41 UTC, rahulreghunath commented on app/Http/Requests/Wisehabit/QuestionSetItemRequest.php
> +            'question_set_id' => 'numeric',
question_set_id is not an optional field, so add required validation

2020-10-17 18:43 UTC, rahulreghunath commented
Complete the edit function in the same pull request :smile:

2020-10-17 18:54 UTC, rahulreghunath requested changes

2020-10-17 18:54 UTC, rahulreghunath commented on routes/web.php
> +    Route::post('question-set-item/new/{id}', [
url for editing should be `question-set-item/{id}/edit`

2020-10-18 18:58 UTC, Midhun-h4r commented on resources/views/wisehabit/question_set_item.blade.php
> +                <option disabled @if(empty(old('question_id' ))) selected @endif>Choose Question Id</option>
done

2020-10-18 19:00 UTC, Midhun-h4r commented on app/Http/Requests/Wisehabit/QuestionSetItemRequest.php
> +            'question_set_id' => 'numeric',
Done

2020-10-19 07:35 UTC, rahulreghunath commented
Edit for form and routes not added please add those asap.

2020-10-19 20:18 UTC, Midhun-h4r commented
#37 
Edit for question set item form and routes  done.

2020-10-20 06:29 UTC, rahulreghunath commented
No further change found. Might be files missing from the commit.

2020-10-20 14:52 UTC, rahulreghunath requested changes

2020-10-20 14:52 UTC, rahulreghunath commented on resources/views/wisehabit/edit_question_set_item.blade.php
> +                <option value="{{$questionSet->id}}" @if(old('question_set_id',$oldData->question_set_id )==$questionSet->id ) selected @endif>{{$questionSet->title}}</option>
Undefined variable: questionSet

did you tested it locally? :unamused:

2020-10-20 14:52 UTC, rahulreghunath commented on resources/views/wisehabit/edit_question_set_item.blade.php
> +                @foreach($questions as $question)
Loops questionSet instead of questions

2020-10-20 15:10 UTC, Midhun-h4r commented on resources/views/wisehabit/edit_question_set_item.blade.php
> +                @foreach($questions as $question)
changed

2020-10-20 15:43 UTC, rahulreghunath commented
**Route [editQuestionSetItem] not defined.**
Test locally and update

2020-10-20 15:45 UTC, rahulreghunath requested changes
Please test locally and update

2020-10-20 15:46 UTC, rahulreghunath commented
Filed should not be edited directly in github

2020-10-23 08:35 UTC, rahulreghunath commented
Also change form to new template

2020-10-23 08:37 UTC, rahulreghunath requested changes

2020-10-23 08:37 UTC, rahulreghunath commented on resources/views/wisehabit/edit_question_set_item.blade.php
> +            <select class="form-control" name="question-set_id" id="question_set_id">
incorrect field name `question-set_id`

2020-10-27 04:39 UTC, rahulreghunath approved these changes

2020-10-27 04:45 UTC, merged